pub mod auth;
pub mod completions;
pub mod config;
pub mod daily;
pub mod describe;
pub mod init;
pub mod logs;
pub mod lua;
#[cfg(feature = "mcp")]
pub mod mcp;
pub mod page;
pub mod picker;
pub mod query;
#[cfg(feature = "skills")]
pub mod schema;
pub mod screenshot;
pub mod server;
pub mod shell;
#[cfg(feature = "skills")]
pub mod skills;
pub mod sync;
pub mod template;
pub mod version;
