//! `sb schema` — emit the full command surface as machine-readable JSON.
//!
//! This is the source of truth agents use to discover sb's capabilities, and it
//! drives `sb skills init` and (where practical) the MCP tool definitions. It is
//! generated by walking the clap `Command` graph, so it can never drift from the
//! real CLI.
//!
//! NOTE: Phase 0 stub — real implementation lands in Phase 3.

use crate::error::{SbError, SbResult};

pub fn execute(_quiet: bool, _color: bool) -> SbResult<()> {
    Err(SbError::NotImplemented)
}
