//! `sb schema` — emit the full command surface as machine-readable JSON.
//!
//! This is the source of truth agents use to discover sb's capabilities, and it
//! drives `sb skills init`. It is generated by walking the clap `Command` graph
//! (`Command::get_subcommands()` / `get_arguments()`), so it can never drift
//! from the real CLI.

use clap::CommandFactory;

use crate::error::SbResult;

pub fn execute(_quiet: bool, _color: bool) -> SbResult<()> {
    let cmd = crate::cli::Cli::command();
    let value = command_to_json(&cmd);
    let root = serde_json::json!({
        "name": cmd.get_name(),
        "version": env!("CARGO_PKG_VERSION"),
        "features": crate::commands::version::compiled_features(),
        "command": value,
    });
    // stdout is the data payload; schema is inherently machine-readable JSON.
    println!("{}", serde_json::to_string_pretty(&root).unwrap());
    Ok(())
}

/// Recursively serialize a clap `Command` (its about text, arguments, and
/// subcommands) to a JSON object.
fn command_to_json(cmd: &clap::Command) -> serde_json::Value {
    let args: Vec<serde_json::Value> = cmd
        .get_arguments()
        // `help`/`version` are auto-injected by clap and not part of sb's surface.
        .filter(|a| a.get_id() != "help" && a.get_id() != "version")
        .map(arg_to_json)
        .collect();

    let subcommands: serde_json::Map<String, serde_json::Value> = cmd
        .get_subcommands()
        .map(|sub| (sub.get_name().to_string(), command_to_json(sub)))
        .collect();

    serde_json::json!({
        "about": cmd.get_about().map(|s| s.to_string()),
        "args": args,
        "subcommands": subcommands,
    })
}

/// Serialize a single clap `Arg`: name, flags, whether it takes a value, whether
/// it is a positional, required-ness, defaults, and help text.
fn arg_to_json(arg: &clap::Arg) -> serde_json::Value {
    use clap::ArgAction;

    // SetTrue/SetFalse/Count/Help/Version actions are valueless (boolean flags);
    // everything else takes at least one value.
    let takes_value = !matches!(
        arg.get_action(),
        ArgAction::SetTrue | ArgAction::SetFalse | ArgAction::Count
    );

    let defaults: Vec<String> = arg
        .get_default_values()
        .iter()
        .map(|v| v.to_string_lossy().into_owned())
        .collect();

    serde_json::json!({
        "name": arg.get_id().as_str(),
        "long": arg.get_long(),
        "short": arg.get_short().map(|c| c.to_string()),
        "positional": arg.is_positional(),
        "required": arg.is_required_set(),
        "takes_value": takes_value,
        "multiple": matches!(arg.get_action(), ArgAction::Append) || arg.get_num_args().map(|n| n.max_values() > 1).unwrap_or(false),
        "defaults": defaults,
        "help": arg.get_help().map(|s| s.to_string()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn command_to_json_includes_top_level_subcommands() {
        let cmd = crate::cli::Cli::command();
        let value = command_to_json(&cmd);
        let subs = value["subcommands"]
            .as_object()
            .expect("subcommands object");
        // A representative sample of sb's surface must be present.
        for name in ["page", "daily", "query", "sync"] {
            assert!(subs.contains_key(name), "missing subcommand: {name}");
        }
    }

    #[test]
    fn page_create_exposes_upsert_flag() {
        let cmd = crate::cli::Cli::command();
        let value = command_to_json(&cmd);
        let create = &value["subcommands"]["page"]["subcommands"]["create"];
        let args = create["args"].as_array().expect("args array");
        let has_upsert = args
            .iter()
            .any(|a| a["name"] == "upsert" && a["long"] == "upsert");
        assert!(
            has_upsert,
            "page create should expose --upsert in the schema"
        );
    }

    #[test]
    fn help_and_version_are_filtered_out() {
        let cmd = crate::cli::Cli::command();
        let value = command_to_json(&cmd);
        let args = value["args"].as_array().unwrap();
        assert!(args
            .iter()
            .all(|a| a["name"] != "help" && a["name"] != "version"));
    }
}
